steps:
  - label: ":junit: Unit Tests"
    command: "./gradlew check --continue ${GRADLE_SWITCHES}"
    agents:
      queue: builder
    plugins:
      docker#v1.1.1:
        image: gradle:6.8.3-jdk8
        always-pull: true
        user: root

  - wait

  - label: ":maven: Publish Artifacts"
    branches: "*.*.*"
    command: "./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository"
    agents:
      queue: builder
    plugins:
      docker#v1.1.1:
        image: gradle:6.8.3-jdk8
        always-pull: true
        user: root
        environment:
          - MAVEN_CENTRAL_SIGNING_KEY
          - MAVEN_CENTRAL_SIGNING_PASSWORD
          - ORG_GRADLE_PROJECT_sonatypeUsername
          - ORG_GRADLE_PROJECT_sonatypePassword
